### use balance
POST http://localhost:8080/transaction/use
Content-Type: application/json

{
  "userId": 1,
  "accountNumber": "1000000002",
  "amount": 100
}

### use balance2
POST http://localhost:8080/transaction/use
Content-Type: application/json

{
  "userId": 1,
  "accountNumber": "1000000002",
  "amount": 100
}

### cancel balance
POST http://localhost:8080/transaction/cancel
Content-Type: application/json

{
  "transactionId": "ca0f6e54ccd8443db01caf65e7b3638b",
  "accountNumber": "1000000002",
  "amount": 10000
}


### query transaciton
GET http://localhost:8080/transaction/5483269f1b93458db75b8fbd7b3f45ce